services:

  postgres:
    container_name: quickmock_postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - quickmock-network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:9
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        GUNICORN_CMD_ARGS: "--limit-request-field_size 16384"
    ports:
        - "5050:80"
    networks:
      - quickmock-network

networks:
  quickmock-network:
    driver: bridge